# Generated by Django 2.1.7 on 2019-03-04 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yukuz_oauth', '0002_uuser_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='person', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ssn', models.PositiveIntegerField(verbose_name='ssn')),
                ('image', models.ImageField(default='def_user', upload_to='', verbose_name='image/def_user')),
                ('phone_number', models.CharField(max_length=15)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='driver', serialize=False, to='yukuz_oauth.Person')),
                ('description', models.TextField(max_length=500, verbose_name='About driver')),
                ('driver_license', models.ImageField(upload_to='licenses/')),
                ('is_active', models.BooleanField(default=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
