# Generated by Django 2.1.7 on 2019-03-04 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yukuz_oauth', '0003_driver_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='phone_number',
        ),
    ]
