# Generated by Django 2.1.7 on 2019-03-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yukuz_oauth', '0005_auto_20190304_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='uuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
