# Generated by Django 2.1.7 on 2019-03-04 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yukuz_oauth', '0006_uuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uuser',
            name='is_active',
        ),
    ]
