# Generated by Django 2.1.7 on 2019-03-04 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('yukuz_oauth', '0003_driver_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('min_kg', models.PositiveIntegerField(default=1)),
                ('max_kg', models.PositiveIntegerField(default=5)),
                ('by_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yukuz_oauth.Person')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveringProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finished', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yukuz_oauth.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='DriverRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(default='')),
                ('star_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yukuz_oauth.Person')),
                ('star_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yukuz_main.DeliveringProcess')),
            ],
        ),
        migrations.CreateModel(
            name='OrderImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='def_user.png', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='PickedOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picked_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=3000)),
                ('weigth', models.FloatField()),
                ('source_address', models.CharField(max_length=300)),
                ('destination_address', models.CharField(max_length=300)),
                ('is_picked', models.BooleanField(default=False)),
                ('deadline', models.DateField()),
                ('estimated_price', models.FloatField(default=0)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('sign', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='postorder',
            name='currency_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yukuz_main.PriceClass'),
        ),
        migrations.AddField(
            model_name='postorder',
            name='order_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yukuz_oauth.Person', verbose_name='order by a person'),
        ),
        migrations.AddField(
            model_name='postorder',
            name='type_of_vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yukuz_main.VehicleType'),
        ),
        migrations.AddField(
            model_name='pickedorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yukuz_main.PostOrder'),
        ),
        migrations.AddField(
            model_name='pickedorder',
            name='picked_by',
            field=models.ManyToManyField(blank=True, to='yukuz_oauth.Driver'),
        ),
        migrations.AddField(
            model_name='orderimages',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_image', to='yukuz_main.PostOrder'),
        ),
        migrations.AddField(
            model_name='deliveringprocess',
            name='picked_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivering_process', to='yukuz_main.PickedOrder'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yukuz_main.VehicleType'),
        ),
    ]
