# Generated by Django 2.1.7 on 2019-03-09 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('yukuz_oauth', '0001_initial'),
        ('yukuz_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postorder',
            name='order_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yukuz_oauth.Person', verbose_name='order by a person'),
        ),
        migrations.AddField(
            model_name='postorder',
            name='type_of_vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yukuz_main.VehicleType'),
        ),
        migrations.AddField(
            model_name='pickedorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yukuz_main.PostOrder'),
        ),
        migrations.AddField(
            model_name='pickedorder',
            name='picked_by',
            field=models.ManyToManyField(blank=True, to='yukuz_oauth.Driver'),
        ),
        migrations.AddField(
            model_name='orderimages',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_image', to='yukuz_main.PostOrder'),
        ),
        migrations.AddField(
            model_name='driverrate',
            name='star_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yukuz_oauth.Person'),
        ),
        migrations.AddField(
            model_name='driverrate',
            name='star_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yukuz_main.DeliveringProcess'),
        ),
        migrations.AddField(
            model_name='deliveringprocess',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yukuz_oauth.Driver'),
        ),
        migrations.AddField(
            model_name='deliveringprocess',
            name='picked_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivering_process', to='yukuz_main.PickedOrder'),
        ),
        migrations.AddField(
            model_name='car',
            name='by_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yukuz_oauth.Person'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yukuz_main.VehicleType'),
        ),
    ]
