# Generated by Django 2.1.7 on 2019-03-04 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yukuz_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveringprocess',
            options={'verbose_name_plural': 'Delivering Processes'},
        ),
        migrations.AlterModelOptions(
            name='priceclass',
            options={'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
    ]
