# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('yukuz_auth', '0002_auto_20171119_0448'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MobDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('device', models.CharField(max_length=512)),
                ('dev_version', models.CharField(max_length=50)),
                ('is_driver', models.BooleanField(default=False)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mfirebase.DeviceType')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yukuz_auth.Person')),
            ],
        ),
    ]
