# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mfirebase', '0002_auto_20171122_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobdevice',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mfirebase.DeviceType'),
        ),
    ]
