# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mfirebase', '0003_auto_20171122_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobdevice',
            name='device',
            field=models.CharField(max_length=512, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mobdevice',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yukuz_auth.Person'),
        ),
    ]
