# Generated by Django 2.1.7 on 2019-03-09 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('yukuz_firebase', '0001_initial'),
        ('yukuz_oauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobdevice',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yukuz_oauth.Person'),
        ),
    ]
