# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firebase', '0001_initial'),
        ('yukuz_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobdevice',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yukuz_auth.Person'),
        ),
    ]
