# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 06:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('yukuz', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='person', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ssn', models.IntegerField()),
                ('image', models.ImageField(default='def_user', upload_to='', verbose_name='image/def_user')),
                ('phone_number', models.CharField(max_length=15)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='driver', serialize=False, to='yukuz_auth.Person')),
                ('driver_license', models.ImageField(upload_to='licenses/')),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yukuz.Car')),
            ],
        ),
    ]
