# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yukuz_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='car',
        ),
        migrations.AddField(
            model_name='driver',
            name='description',
            field=models.TextField(default='about driver', max_length=500, verbose_name='About driver'),
            preserve_default=False,
        ),
    ]
