# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yukuz_auth', '0002_auto_20171119_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
