# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yukuz_auth', '0003_driver_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
