# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
                ('min_kg', models.PositiveIntegerField(default=1)),
                ('max_kg', models.PositiveIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('ssn', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PickedOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='yukuz.Driver')),
                ('picked_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=3000)),
                ('weigth', models.FloatField()),
                ('source_address', models.CharField(max_length=300)),
                ('destination_address', models.CharField(max_length=300)),
                ('is_picked', models.BooleanField(default=False)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('order_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yukuz.Person', verbose_name='order by a person')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='pickedorder',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='yukuz.PostOrder'),
        ),
        migrations.AddField(
            model_name='driver',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yukuz.Car'),
        ),
        migrations.AddField(
            model_name='driver',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='yukuz.Person'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='yukuz.VehicleType'),
        ),
    ]
