# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yukuz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='avatar',
            field=models.ImageField(default='images/def_user.png', upload_to='images/', verbose_name='human avatar'),
        ),
    ]
