# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yukuz', '0002_postorder_is_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='id',
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_license',
            field=models.ImageField(default='', upload_to='licenses/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='yukuz.Person'),
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ava', serialize=False, to='yukuz.Person'),
        ),
    ]
