# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 03:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yukuz', '0002_auto_20171014_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('device', models.CharField(max_length=512)),
                ('dev_version', models.CharField(max_length=50)),
                ('is_driver', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='yukuz.DeviceType'),
        ),
        migrations.AddField(
            model_name='device',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
