# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yukuz', '0002_auto_20171116_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default='def_user.png', upload_to='vehicles/'),
        ),
    ]
