# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yukuz', '0003_car_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
    ]
