# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yukuz', '0004_auto_20171029_0523'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='postorder',
            name='deadline',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='postorder',
            name='estimated_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='postorder',
            name='image',
            field=models.FileField(default='/images/def_user.png', upload_to='images'),
        ),
        migrations.AddField(
            model_name='postorder',
            name='currency_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='yukuz.PriceClass'),
        ),
    ]
