# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yukuz_auth', '0004_auto_20171123_1207'),
        ('yukuz', '0005_auto_20171119_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickedorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yukuz.PostOrder'),
        ),
        migrations.RemoveField(
            model_name='pickedorder',
            name='picked_by',
        ),
        migrations.AddField(
            model_name='pickedorder',
            name='picked_by',
            field=models.ManyToManyField(blank=True, to='yukuz_auth.Driver'),
        ),
    ]
