# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yukuz', '0006_auto_20171029_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postorder',
            name='image',
        ),
    ]
