# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yukuz_auth', '0004_auto_20171123_1207'),
        ('yukuz', '0006_auto_20171129_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveringProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finished', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField(blank=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yukuz_auth.Driver')),
                ('picked_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yukuz.PickedOrder')),
            ],
        ),
    ]
