# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yukuz', '0007_auto_20170926_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(default='')),
                ('star_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yukuz.Person')),
                ('star_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yukuz.PickedOrder')),
            ],
        ),
    ]
