# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yukuz', '0007_remove_postorder_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderimages',
            name='image',
            field=models.ImageField(default='def_user.png', upload_to='images/'),
        ),
    ]
