# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yukuz', '0007_deliveringprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveringprocess',
            name='picked_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivering_process', to='yukuz.PickedOrder'),
        ),
        migrations.AlterField(
            model_name='driverrate',
            name='star_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yukuz.DeliveringProcess'),
        ),
    ]
