# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yukuz', '0008_auto_20171031_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderimages',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_image', to='yukuz.PostOrder'),
        ),
    ]
