# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yukuz', '0008_auto_20171129_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveringprocess',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
