# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yukuz', '0009_auto_20171101_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='postorder',
            name='type_of_vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='yukuz.VehicleType'),
            preserve_default=False,
        ),
    ]
