# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yukuz', '0010_postorder_type_of_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postorder',
            old_name='title',
            new_name='post_title',
        ),
    ]
