# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yukuz', '0012_auto_20171105_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postorder',
            name='currency_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yukuz.PriceClass'),
        ),
    ]
