# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yukuz', '0014_auto_20171105_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='by_person',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='yukuz.Person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_license',
            field=models.ImageField(upload_to='licenses/'),
        ),
        migrations.AlterField(
            model_name='postorder',
            name='deadline',
            field=models.DateField(),
        ),
    ]
