# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yukuz', '0015_auto_20171113_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='id',
        ),
        migrations.AlterField(
            model_name='car',
            name='number',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
