# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yukuz', '0016_auto_20171113_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='title',
            field=models.CharField(default='Damas', max_length=50),
            preserve_default=False,
        ),
    ]
